language: python
python:
  - "3.6"
# command to install dependencies
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - cd envs
  - conda create --name galana
# command to run tests
script:
  - source activate galana
  - pip install coveralls
  - pip install sphinx
  - conda install -y --quiet --yes \
    'numpy' \
    'pandas' \
    'tensorflow' \
    'pytest' \
    'pytest-cov' \
    'keras' \
    'pillow'
  - conda clean -tipsy
  - pip install pytest-cov
  - conda install -y -c astropy astroquery
  - pip uninstall -y keras-preprocessing
  - pip install git+https://github.com/keras-team/keras-preprocessing.git
  - python -m pytest --cov=galana/ -W ignore::DeprecationWarning
  - cd docs
  - make html
  - cd ..
after_success:
  - coveralls
